services:
  go:
    image: golang:1.21
    volumes:
      - .:/work
      - go_mod_cache:/go/pkg/mod
      - go_build_cache:/root/.cache/go-build/
    working_dir: /work
    entrypoint: go

  buf:
    image: bufbuild/buf:1.29.0
    volumes:
      - .:/work
    working_dir: /work/proto
    entrypoint: buf

volumes:
  go_mod_cache:
  go_build_cache:
