name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        type: string
        required: true
        default: latest
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - prd
          - stg

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.version }} - ${{ inputs.environment }}"